/*
 * @Author: Dermot Rogan
 * @Author: Jimmy Treanor
 * @Project: LibaryApp_BookStoreCA
 */

package Encryption;


import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.KeySpec;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;


/**
 * @author Dermot
 * @author Jimmy
 */
public class SaltedPasswords {

    /**
     *
     * @return salt
     */
    public static byte[] generateSalt() {
        //Create our secure random object
        SecureRandom secRand = new SecureRandom();
        //Create byte array to hold our salt
        byte salt[] = new byte[32];
        //Fill our array with randomly generated bytes
        secRand.nextBytes(salt);
        //Return our salt
        return salt;
    }

    /**
     *
     * @param input
     * @return generated Hash
     */
    public static String generateHash(String input) {
        StringBuilder hash = new StringBuilder();

        try {
            MessageDigest sha = MessageDigest.getInstance("SHA-256");
            byte[] hashedBytes = sha.digest(input.getBytes());
            char[] digits = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
                'a', 'b', 'c', 'd', 'e', 'f','g','h','i','j','k','l','m','n','o','p','q','r','u','s','t','w','x','y','z'};
            for (int idx = 0; idx < hashedBytes.length; ++idx) {
                byte b = hashedBytes[idx];
                hash.append(digits[(b & 0xf0) >> 4]);
                hash.append(digits[b & 0x0f]);
            }
        } catch (NoSuchAlgorithmException e) {
            // handle error here.
        }

        return hash.toString();
    }
    
    /**
     *
     * @param password
     * @param salt
     * @return salted hash of salt and pass
     */
    public static byte[] generateSaltedHash(String password, byte[] salt) {
        StringBuilder hash2 = new StringBuilder();
        //Create an array to hold our hash
        byte[] hash = null;
        //Create new Key Spec (More Below)
        KeySpec spec = new PBEKeySpec(password.toCharArray(), salt, 65563, 256);
        try {
            SecretKeyFactory keyFactory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA512");
            hash = keyFactory.generateSecret(spec).getEncoded();
        } catch (NoSuchAlgorithmException ex) {
            System.out.println("No algorith found matching that pattern");
        } catch (InvalidKeySpecException ex) {
            System.out.println("Key spec chosen is invalid");
        }

        //Return hash
        return hash; 
    }

}

